arch = {
	packages = [
		"base",
		"base-devel",
		"blesh",
		"btrfs-progs",
		"fastfetch",
		"ffmpeg",
		"fuse2",
		"fzf",
		"git",
		"go",
		"grub",
		"htop",
		"jq",
		"keepassxc",
		"libev",
		"linux",
		"linux-firmware",
		"man-db",
		"man-pages",
		"metapac",
		"neovim",
		"networkmanager",
		"nmap",
		"noto-fonts-cjk",
		"npm",
		"openssh",
		"openssh",
		"pacdef-bin",
		"podman",
		"python-pipenv",
		"ripgrep",
		"rustup",
		"slurp",
		"syncthing-bin",
		"tailscale",
		"tmux",
		"unrar",
		"unzip",
		"wl-clipboard",
		"xorg-xhost",
		"yay-bin",
		"yt-dlp",
		"zip",
	]
}
