arch = {
	packages = [
		"alacritty",
		"bluetuith-bin",
		"bluez-utils",
		"brave-bin",
		"discord",
		"evince",
		"gnome-boxes",
		"gnome-calculator",
		"gnome-disk-utility",
		"grim",
		"gst-plugin-pipewire",
		"hyprland",
		"imv",
		"libpulse",
		"lutris",
		"mako",
		"monero-gui",
		"network-manager-applet",
		"onlyoffice-bin",
		"pavucontrol",
		"pipewire",
		"pipewire-alsa",
		"pipewire-jack",
		"pipewire-pulse",
		"protonup-qt",
		"qbittorrent",
		"steam",
		"thunar",
		"tofi",
		"torbrowser-launcher",
		"vlc",
		"waybar",
		"wine",
		"wireplumber",
		"wlr-randr",
		"wpaperd",
		"xdg-desktop-portal-hyprland",
		"xorg-xwayland",
	]
}
