enabled_backends = ["arch"]
hostname_groups_enabled = true

[hostname_groups]
archlinux = ["default", "gui"]
bird = ["default", "gui", "amd"]
eaglego = ["default", "gui", "mobile", "nvidia"]

[arch]
package_manager = "yay"


